#!/usr/bin/env python3
import argparse
import marko
import string
import sys

###########################################
def process_header(ast):
    """process_header() -> dict()

Processes header and returns a dict().
"""
    pass


###########################################
if __name__ == '__main__':
    parser = argparse.ArgumentParser(
                description="??????????????????????")
    parser.add_argument("file", nargs="?",
                        help="input markdown file",
                        type=argparse.FileType('r'), default=sys.stdin)
    parser.add_argument('-t', '--template', type=argparse.FileType('r'),
                        required=True,
                        help="path to template file")

    args = parser.parse_args()
    template = string.Template(args.template.read())
    mapping = {'aspectratio': '169', 'title': 'BUM', 'shorttitle': 'BAC', 'slides': 'WIP'}
    result = template.substitute(mapping)
    print(result)

    doc = marko.Markdown()
    ast = doc.parse(args.file.read())

    for child in ast.children:
        print(child)

    header = process_header(ast)

    # with open(args.fila, "r") as file:
    #     doc = marko.Markdown()
    #     ast = doc.parse(file.read())
    #     print(ast)
    #
    #     header = process_header(ast)
